name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: npm ci --no-audit
    - run: npm run lint --if-present
    - run: npm test
    - run: npm run build --if-present
      env:
        CI: true
